spring:
  application:
    name: crud-operation-demo

  datasource:
    url: jdbc:mysql://localhost:3306/crud
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

jwt:
  secret: ${JWT_SECRET:c2VjdXJlLXNhbXBsZS1qd3Qtc2VjcmV0LWtleS0xMjM0NTY3ODk=}


  spring:
    main:
      allow-circular-references=true: